name: Java unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ref: 'main'

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        architecture: 'x64'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build


